name: apiverve_callingcode
description: Country Calling Code is a simple tool for getting the country's international dialing codes. It returns the country's international dialing codes.
version: 1.1.14
homepage: https://apiverve.com/marketplace/callingcode?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/callingcode-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
